-- UNITDEF -- ECLIPSE --
--------------------------------------------------------------------------------

local unitName = "eclipse"

--------------------------------------------------------------------------------

local unitDef = {
  acceleration       = .04,
  airHoverFactor     = 0,
  airStrafe          = false,
  autoheal		   = 20,
  brakeRate          = .5,
  canAttack          = true,
  canDGun            = true,
  canFly             = true,
  canMove            = true,
  canstop            = "1",
  category           = "LARGE STRONG TARGET ANY",
  collide            = false,
  collisionvolumescales = "104 64 272",
  collisionvolumetype = "Box",
  cruiseAlt          = 80,
  description        = "Heavy assault battleship",
  explodeAs          = "RetroDeathBig",
  footprintX         = 8,
  footprintZ         = 8,
  hoverAttack        = true,
  iconType           = "comet",
  idleAutoHeal       = 0,
  idleTime           = 0,
  levelGround        = false,
  mass               = 10000,
  maxDamage          = 42000,
  maxVelocity        = 1.6,
  name               = "Eclipse",
  noChaseCategory    = "NOCHASE",
  objectName         = "Eclipse.s3o",
  power              = 6000,
  radarDistance      = 0,
  selfDestructAs     = "ImperatorDeath",
  selfDestructCountdown = 10,
  showNanoFrame      = false,
  side               = "ALL",
  sightDistance      = 1200,
  smoothAnim         = false,
  turnRate           = 220,
  unitname           = "eclipse",
  customparams = {
    buildTime          = 120,
    cost               = "14000",
    type               = "large",
  },
  sfxtypes = {
    explosiongenerators = {
      "custom:death_med",
      "custom:death_large",
      "custom:death_multimed",
      "custom:teleport",
      "custom:muzzlekinetic",
      "custom:muzzlemassdriver",
    },
  },
  sounds = {
    arrived = {
      "commandgiven",
    },
    ok = {
      "commandgiven",
    },
    select = {
      "select",
    },
  },
  weapons = {
	--Antimatter beam
    [1]  = {
      def                = "EclipseAMBeamPrimer",
      mainDir            = "0 0 1",
      maxAngleDif        = 120,
      onlyTargetCategory = "WEAK STRONG",
    },
    [2]  = {
      def                = "EclipseAMBeam",
      onlyTargetCategory = "VOID",
    },
	--Megalaser primer(dgun weapon)
    [3]  = {
      def                = "MegaLaserPrimer",
      --mainDir            = "0 0 1",
      --maxAngleDif        = 25,
      badTargetCategory  = "SMALL WEAK",
      onlyTargetCategory = "TARGET",
    },
	---Gravy gun
	[4]  = {
      def                = "GEclipse",
      onlyTargetCategory = "LARGE",
    },
	--Kinetic blasters
    [5]  = {
	  def                = "KMedium",
      badTargetCategory  = "LARGE",
      onlyTargetCategory = "TARGET",
    },
	[6]  = {
	  def                = "KMedium",
      badTargetCategory  = "LARGE",
      onlyTargetCategory = "TARGET",
    },
	[7]  = {
	  def                = "KMedium",
      badTargetCategory  = "LARGE",
      onlyTargetCategory = "TARGET",
    },
	[8]  = {
	  def                = "KMedium",
      badTargetCategory  = "LARGE",
      onlyTargetCategory = "TARGET",
    },
	[9]  = {
	  def                = "KMedium",
      badTargetCategory  = "LARGE",
      onlyTargetCategory = "TARGET",
    },
	[10]  = {
	  def                = "KMedium",
      badTargetCategory  = "LARGE",
      onlyTargetCategory = "TARGET",
    },
	[10]  = {
	  def                = "KMedium",
      badTargetCategory  = "LARGE",
      onlyTargetCategory = "TARGET",
    },
	--Point defense
    [11]  = {
      def                = "MPointDefense",
      onlyTargetCategory = "TINY",
    },
	[12]  = {
      def                = "MPointDefense",
      onlyTargetCategory = "TINY",
    },
	[13]  = {
      def                = "MPointDefense",
      onlyTargetCategory = "TINY",
    },
	[14]  = {
      def                = "MPointDefense",
      onlyTargetCategory = "TINY",
    },
	--Gravy flak
    [15]  = {
	  def                = "GFlakEclipse",
      badTargetCategory  = "LARGE",
    },
	--Rear plasma cannons
	[16]  = {
	  def                = "PHeavy",
      badTargetCategory  = "SMALL TORPEDO",
      mainDir            = "-0.2 0 -1",
      maxAngleDif        = 90,
      onlyTargetCategory = "TARGET",
    },
	[17]  = {
	  def                = "PHeavy",
      badTargetCategory  = "SMALL TORPEDO",
      mainDir            = "0.2 0 -1",
      maxAngleDif        = 90,
      onlyTargetCategory = "TARGET",
    },
	--Drone controllers
    [18]  = {
      def                = "DroneMarker",
      onlyTargetCategory = "TARGET",
    },
    [19]  = {
      def                = "DroneMarker",
      onlyTargetCategory = "TARGET",
    },
	--Torpedoes
    [20]  = {
      def                = "TEclipse",
      onlyTargetCategory = "TARGET",
    },
	--Missile launchers
    [21]  = {
      def                = "MEclipse",
      onlyTargetCategory = "TARGET",
    },
    [22]  = {
      def                = "MEclipse",
      onlyTargetCategory = "TARGET",
    },
	--The ultimate weapon
    [23]  = {
      def                = "MegaLaser",
      onlyTargetCategory = "VOID",
    },	
  },
}


--------------------------------------------------------------------------------

local weaponDefs = {
  GFlakEclipse = {
    areaOfEffect       = 150,
    avoidFeature       = false,
    avoidFriendly      = false,
    beamburst          = true,
    burnblow           = true,
    burst              = 4,
    burstrate          = .06,
    collideFeature     = false,
    collideFriendly    = false,
    craterBoost        = 0,
    craterMult         = 0,
    explosionGenerator = "custom:grav",
    explosionSpeed     = 65536,
    impulseBoost       = 0,
    impulseFactor      = 0,
    interceptedByShieldType = 8,
    minIntensity       = 1,
    myGravity          = .001,
    name               = "Grav Flak",
    noSelfDamage       = true,
    range              = 750,
    reloadtime         = .65,
    rgbColor           = "1 1 1",
    soundHit           = "grav",
    thickness          = 1,
    tolerance          = 3000,
    turret             = true,
    weaponType         = "BeamLaser",
    weaponVelocity     = 900,
    damage = {
      default            = 20,
    },
  },
  GEclipse = {
    areaOfEffect       = 50,
    avoidFeature       = false,
    avoidFriendly      = true,
    beamburst          = true,
    beamTTL            = 2,
    burst              = 10,
    burstrate          = .06,
    collideFeature     = false,
    collideFriendly    = false,
    craterBoost        = 0,
    craterMult         = 0,
    explosionGenerator = "custom:grav",
    explosionSpeed     = 600,
    impulseBoost       = 0,
    impulseFactor      = 0,
    intensity          = 1,
    interceptedByShieldType = 8,
    name               = "Gravitrics",
    noSelfDamage       = true,
    range              = 575,
    reloadtime         = 3,
    rgbColor           = "0 0 0",
    soundHit           = "",
    soundStart         = "grav",
    thickness          = 8,
    tolerance          = 9000,
    turret             = true,
    weaponType         = "BeamLaser",
    damage = {
      default            = 600,
    },
  },
  EclipseAMBeam = {
    areaOfEffect       = 24,
    avoidFeature       = false,
    avoidFriendly      = false,
    beamburst          = true,
    beamDecay          = .7,
    beamTTL            = 4,
    collideFeature     = false,
    collideFriendly    = false,
    craterBoost        = 0,
    craterMult         = 0,
    explosionGenerator = "custom:antimatter",
    impulseBoost       = 0,
    impulseFactor      = 0,
    intensity          = 1,
    interceptedByShieldType = 4,
    largeBeamLaser     = true,
    laserFlareSize     = 4,
    minIntensity       = 1,
    name               = "Antimatter Beam",
    noSelfDamage       = true,
    range              = 1400,
    reloadtime         = 10,
    rgbColor           = "1 1 1",
    soundHit           = "",
    soundStart         = "llaser",
    thickness          = 18,
    tolerance          = 1000,
    turret             = true,
    weaponType         = "BeamLaser",
    damage = {
      default            = 65,
    },
  },
  EclipseAMBeamBeamPrimer = {
    areaOfEffect       = 24,
    avoidFeature       = false,
    avoidFriendly      = false,
    beamburst          = true,
    beamDecay          = .7,
    beamTTL            = 4,
    collideFeature     = false,
    collideFriendly    = false,
    craterBoost        = 0,
    craterMult         = 0,
    explosionGenerator = "custom:antimatter",
    impulseBoost       = 0,
    impulseFactor      = 0,
    intensity          = 1,
    interceptedByShieldType = 4,
    largeBeamLaser     = true,
    laserFlareSize     = 4,
    minIntensity       = 1,
    name               = "Antimatter Beam",
    noSelfDamage       = true,
    projectiles        = 0,
    range              = 1400,
    reloadtime         = 10,
    rgbColor           = "1 1 1",
    soundHit           = "",
    soundStart         = "llaser",
    thickness          = 18,
    tolerance          = 1000,
    turret             = true,
    weaponType         = "BeamLaser",
    damage = {
      default            = 65,
    },
  },
  MPointDefense = {
    areaOfEffect       = 12,
    avoidFeature       = false,
    avoidFriendly      = false,
    beamburst          = true,
    beamDecay          = .9,
    beamTTL            = 24,
    collideFeature     = false,
    collideFriendly    = false,
    craterBoost        = 0,
    craterMult         = 0,
    explosionGenerator = "custom:laser",
    fallOffRate        = .05,
    impulseBoost       = 0,
    impulseFactor      = 0,
    intensity          = 1,
    interceptedByShieldType = 1,
    minIntensity       = 1,
    name               = "Point Defense",
    noSelfDamage       = true,
    range              = 850,
    reloadtime         = .5,
    rgbColor           = "0 1 0",
    size               = 2,
    soundHit           = "klighthit",
    thickness          = 4,
    tolerance          = 30000,
    turret             = true,
    weaponType         = "BeamLaser",
    weaponVelocity     = 1200,
    damage = {
      default            = 2,
      drone              = "45",
      torpedo            = "45",
    },
  },
  TEclipse = {
    areaOfEffect       = 8,
    craterBoost        = 0,
    craterMult         = 0,
    impulseBoost       = 0,
    impulseFactor      = 0,
    interceptedByShieldType = 0,
    name               = "Torpedo Launch Control",
    projectiles        = 0,
    range              = 1200,
    reloadtime         = 8,
    tolerance          = 3000,
    turret             = true,
    weaponType         = "Melee",
    damage = {
      default            = .0001,
    },
  },
  MEclipse = {
    areaOfEffect       = 64,
    avoidFeature       = false,
    avoidFriendly      = false,
    burnblow           = true,
    cegTag             = "trail_missile",
    collideFeature     = false,
    collideFriendly    = false,
    craterBoost        = 0,
    craterMult         = 0,
    explosionGenerator = "custom:missile",
    fixedLauncher      = true,
    flightTime         = 1,
    guided             = "1",
    impulseBoost       = 0,
    impulseFactor      = 0,
    interceptedByShieldType = 2,
    model              = "missile_small.s3o",
    name               = "Light Missile Pack",
    noSelfDamage       = true,
	projectiles		   = 2,
    range              = 475,
    reloadtime         = 2,
    smokeTrail         = true,
    soundHit           = "mlighthit",
    soundStart         = "mlightfire",
    startVelocity      = 400,
    targetBorder       = 1,
    tolerance          = 3000,
    tracks             = true,
    turnRate           = 22000,
    turret             = true,
    weaponAcceleration = 100,
    weaponType         = "MissileLauncher",
    weaponVelocity     = 400,
    damage = {
      default            = 120,
    },
  },
  
  MegaLaser = {
    areaOfEffect       = 64,
    avoidFeature       = false,
    avoidFriendly      = false,
    beamburst          = true,
    beamDecay          = .7,
    beamTTL            = 4,
    collideFeature     = false,
    collideFriendly    = false,
    commandfire             = true,
    craterBoost        = 0,
    craterMult         = 0,
    explosionGenerator = "custom:antimatter",
    impulseBoost       = 0,
    impulseFactor      = 0,
    intensity          = 1,
    interceptedByShieldType = 4,
    largeBeamLaser     = true,
    laserFlareSize     = 4,
    minIntensity       = 1,
    name               = "Megalaser",
    noExplode	     = true,
    noSelfDamage       = true,
    range              = 1800,
    reloadtime         = 30,
    rgbColor           = "1 1 1",
    soundHit           = "",
    soundStart         = "llaser",
    thickness          = 30,
    tolerance          = 1000,
    turret             = false,
    weaponType         = "BeamLaser",
    damage = {
      default            = 300,
    },
  },
  MegaLaserPrimer = {
    areaOfEffect       = 24,
    avoidFeature       = false,
    avoidFriendly      = false,
    beamburst          = true,
    beamDecay          = .7,
    beamTTL            = 4,
    collideFeature     = false,
    collideFriendly    = false,
    commandfire        = true,
    craterBoost        = 0,
    craterMult         = 0,
    explosionGenerator = "custom:antimatter",
    impulseBoost       = 0,
    impulseFactor      = 0,
    intensity          = 1,
    interceptedByShieldType = 4,
    largeBeamLaser     = true,
    laserFlareSize     = 4,
    minIntensity       = 1,
    name               = "Megalaser",
    noExplode	     = true,
    noSelfDamage       = true,
    projectiles        = 0,
    range              = 1800,
    reloadtime         = 30,
    rgbColor           = "1 1 1",
    soundHit           = "",
    soundStart         = "llaser",
    thickness          = 30,
    tolerance          = 1000,
    turret             = false,
    weaponType         = "BeamLaser",
    damage = {
      default            = 200,
    },
  },
}
unitDef.weaponDefs = weaponDefs


--------------------------------------------------------------------------------

return lowerkeys({ [unitName] = unitDef })

--------------------------------------------------------------------------------
